image: debian/testing
packages:
  - emacs
  - rsync
  - texinfo
  - texlive
sources:
  - https://git.sr.ht/~codegouvfr/documentation
secrets:
  - bdd50953-add5-4ddb-9f34-9f0781900b7e
tasks:
  - install: |
      cd documentation/
      emacs --script scripts/publish.el
      texi2pdf index.texi
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av documentation/* web@code.gouv.fr:/home/web/websites/documentation/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@code.gouv.fr
