image: debian/testing
packages:
  - emacs
  - org-mode
  - rsync
  - texinfo
  - texlive-full
  - python3
  - pip
  - pipenv
sources:
  - https://git.sr.ht/~codegouvfr/documentation
secrets:
  - bdd50953-add5-4ddb-9f34-9f0781900b7e
tasks:
  - make_mkdocs: |
      cd documentation/
      pipenv install --index gitlab mkdocs-dsfr
      pipenv install
      pipenv shell
      make md
  - make_pdf: |
      cd documentation/
      make pdf
      mv index.pdf public/logiciels-libres-et-administration-publique.pdf
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av documentation/public/* web@code.gouv.fr:/home/web/websites/documentation/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@code.gouv.fr
