#+title: Documentation de la mission logiciels libres
#+author: Équipe de la mission logiciels libres
# #+date: <2023-07-21 ven.>

* Préambule

Un préambule.

* Publier un code source

** Cadre juridique

Toute entité chargée d'une mission de service public doit publier tout
document produit ou reçu dans le cadre de cette mission, quelle qu'en
soit la date, le lieu de conservation et le support. Les codes
sources, en tant que documents administratifs, relèvent de cette
obligation (voir l'avis CADA du 8 janvier 2015 n°[[http://cada.data.gouv.fr/20144578/][20144578]]).

Les codes sources concernés sont, au même titre que n'importe quelle
autre donnée administrative publiable en open data, celles « dont la
publication présente un intérêt économique, social, sanitaire ou
environnemental. »

Pour les licences, voir les articles [[https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=BCCCCF5B5E15C3F6CABA0952E9B5A818.tplgfr21s_3?idArticle=LEGIARTI000033219073&cidTexte=LEGITEXT000031366350&dateTexte=20190307][L323-2]] et [[https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=6A856B120BAA63F8153E8D6C8CDF40D4.tplgfr21s_3?idArticle=LEGIARTI000034504991&cidTexte=LEGITEXT000031366350&dateTexte=20190307][D323-2-1]] du Code des
relations entre le public et les administrations.

*** Pour qu'un code source soit communicable

- L'obligation de communicabilité porte sur les collectivités de plus
  de 3500 habitants et les organismes publics de plus de 50 agents.

- L'organisme public ouvrant le code source doit en avoir la propriété
  intellectuelle.

- Le code source doit être « achevé » : dès lors qu'une version du
  code est mise en oeuvre dans l'administration, cette version est
  considérée comme « achevée ». Notamment une version dite bêta ou
  inférieure à 1.0, si elle est effectivement utilisée, est bien
  achevée et communicable.

- Sa communication ne doit pas porter atteinte :

  - au secret commercial et industriel ;
  - à la sûreté de l'État, à la sécurité publique, à la sécurité des
    personnes ou à la sûreté des systèmes d'information des
    administrations ;
  - à la recherche et à la prévention, par les services compétents,
    d'infractions de toute nature.

En dehors de ces limites, toute personne ou toute administration peut
demander la communication d'un code source.

*** Licences applicables à la publication d'un code source

La liste des licences sous lesquelles un code source peut être placé
au moment de sa diffusion est [[https://www.data.gouv.fr/fr/licences][accessible ici]].

*** Guide juridique interactif

Pour savoir si le code source d'un logiciel développé et utilisé par
votre organisme public est communicable, nous vous invitons à tester
ce [[https://guide-juridique-logiciel-libre.etalab.gouv.fr/][guide juridique interactif]].

** Quels degrés d'ouverture pour les codes sources ?

- *📘 Niveau A - contributif :* Le code source est publié, les
  contributions extérieures sont activement recherchées et traitées.

- *📗 Niveau B - ouvert :* Le code source est publié, les contributions
  extérieures sont traitées mais non activement recherchées.

- *📙 Niveau C - publié:* Le code source est publié mais les
  contributions extérieures ne sont pas traitées.

- *📕 Niveau D - non-communicable:* Le code source n'est pas
  communicable au public.

** Quels logiciels ouvrir à quel degré ?

Tous les logiciels développés par un organisme public n'ont pas
vocation à être ouverts au même degré.

Nous proposons trois critères :

1. Le logiciel est-il *un module utile à d'autres logiciels libres* (ou
   un logiciel « monolithique » sans utilité pour d'autres logiciels
   libres) ?

2. Le logiciel répond-il a un *besoin générique* (ou à un besoin
   spécifique à l'organisme qui le produit) ?

3. L'*utilisateur final* du logiciel a-t-il un profil technique
   (développeur, datascientiste ou designer) ?

*Le niveau A* est recommandé pour les logiciels répondant à au moins
deux critères ; le niveau B est recommandé pour ceux répondant à au
moins un critère ; le niveau C pour ceux ne répondant à aucun de ces
trois critères (par ex. un logiciel métier très spécifique, dont
aucune partie ne peut être réutilisée ailleurs et dont les
utilisateurs ne sont pas du tout des contributeurs potentiels.)

Pour les logiciels ne répondant à aucun des trois critères, le niveau
D est admissible, tant qu'aucun citoyen n'exige la communication du
code source en question, selon le cadre juridique défini dans la loi
pour République numérique.

Bien sûr, ces critères sont *relatifs* : la modularité, la généricité et
le potentiel de contribution des utilisateurs ne s'évaluent pas dans
l'absolu.  Ces notions aident seulement à *prioriser les ouvertures
logicielles*.  Le but est de *canaliser son énergie* sur les logiciels
qui ont un bon potentiel contributif et *de communiquer clairement* sur
la posture de l'administration dans le cas des publications simples.

*** Exemples de mise en oeuvre

- Une collectivité territoriale développe un outil de correction
  grammaticale pour LibreOffice.  Ce logiciel est un module d'un
  logiciel libre existant et il répond à un besoin générique : il est
  pertinent d'en faire un *logiciel libre « contributif »* (niveau A).

- Une administration développe un outil pour organiser la collecte de
  données sur le web (*scraping*).  C'est un outil web « monolithique »
  mais qui répond à un besoin rencontré hors de l'administration : il
  peut être publié comme *logiciel libre « ouvert »* (niveau B).

- Une administration centrale développe un thème pour les sites
  qu'elle publie à l'aide de Jekyll.  Ce thème est un module d'un
  logiciel libre existant mais il répond à un besoin spécifique de
  l'organisme public : son code source peut être publié, mais sans
  recherche active de contributeurs ni maintenance particulière à
  l'égard des contributions extérieures (niveau C).

Chaque organisme peut tenter de prioriser les logiciels à ouvrir
en fonction de ces critères.

** Bonnes pratiques de publication

* Utiliser des logiciels libres
* Monter un "Open Source Programme Office"

** Définir une stratégie open source

** Qu'est-ce qu'un "Open Source Programme Office"?

Voir https://code.gouv.fr/fr/blog/definition-ospo/.

Voir http://preprod.codegouv.studio/choices-ospo/.

** Sites web d'organismes publics engagés

- https://opensource.amue.fr
- https://opensource.paris.fr
- https://www.health-data-hub.fr/open-source
- https://www.france-universite-numerique.fr
- https://socialgouv.github.io

** Politiques logiciels libres

- https://www.culture.gouv.fr/Thematiques/Innovation-numerique/Publications/Politique-du-ministere-de-la-Culture-pour-les-codes-sources-algorithmes-et-logiciels-libres
- https://www.health-data-hub.fr/open-source
- https://medialab.sciencespo.fr/a-propos/#deontology
- https://github.com/abes-esr/abes-politique-developpement
- https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-fais-des-choix-technologique/licences
- https://www.etalab.gouv.fr/accompagnement-logiciels-libres

* Foire aux questions

** Qu'est-ce qu'un logiciel libre ?

Un logiciel est dit libre si son code source est publié sous l'une des
licences reconnue libre soit par la Free Software Foundation soit par
l'Open Source Initiative.  Une licence libre octroie quatre libertés :

- la liberté d'utiliser le logiciel
- la liberté de copier le logiciel
- la liberté d'étudier le logiciel
- la liberté de modifier le logiciel et de redistribuer les versions modifiées

Voir https://spdx.org/licenses/ pour la liste des licences et de leur
validation par l'OSI ou la FSF.

** Qui peut m'aider à publier mes codes sources ?

Vous pouvez interroger vos collègues et votre direction pour savoir si
vous disposez d'une forge et/ou de comptes d'organisation dédiés où
publier vos codes sources.

À défaut de réponse, vous pouvez solliciter l'Administrateur
Ministériel des Données, des Algorithmes et des Codes sources de votre
ministère.  Voir [[https://www.data.gouv.fr/fr/datasets/liste-des-administrateurs-ministeriels-des-donnees-des-algorithmes-et-des-codes-sources/][la liste des AMDACs]].

** Sous quelle licence dois-je publier mes codes sources ?

En tant que mission de service public, la loi pour une République
numérique exige la publication des codes sources sous l'une des
licences référencées à l'[[https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000034504993][article D323-2-2]] du Code des Relations entre
le Public et les Administrations.

Le portail data.gouv.fr présente ces [[https://www.data.gouv.fr/fr/pages/legal/licences/][licences de réutilisations]], pour
les données comme pour les logiciels.

Licences permissives :

- Apache License 2.0
- BSD 2-Clause "Simplified" License
- BSD 3-Clause "New" or "Revised" License
- CeCILL-B Free Software License Agreement
- MIT License

Licences à réciprocité :

- CeCILL Free Software License Agreement v2.1
- CeCILL-C Free Software License Agreement
- GNU General Public License v3.0 or later
- GNU Lesser General Public License v3.0 or later
- GNU Affero General Public License v3.0 or later
- Mozilla Public License 2.0
- Eclipse Public License 2.0
- European Union Public License 1.2

Vous devez prioriser le choix d'une licence permissive et n'utiliser
de licence à réciprocité que si la publication sous licence permissive
présente un risque duement justifié pour l'intérêt général.

** Comment contacter la mission logiciels libres ?

=contact@code.gouv.fr=

** Quelle forge dois-je choisir pour publier mes codes sources ?
** Comment attirer des contributeurs sur mes dépôts publiés ?
** Suis-je obligé de permettre la contribution sur mes dépôts ?

Non.

** Puis-je publier un code que je ne maintiens plus ?

Oui.  Dans ce cas, indiquez bien dans le fichier ~README~ que le code
source n'est plus maintenu.

Si vous le souhaitez, vous pouvez préciser dans ce ~README~ qu'un
nouveau mainteneur est recherché.

** Le prestataire doit-il m'envoyer le code source qu'il a développé pour moi ?

Oui.

** Où trouver tous les dépôts publiés par mon ministère ?

Vous pouvez chercher sur [[https://code.gouv.fr/public/#/groups][code.gouv.fr]] l'organisation qui correspond à
votre direction ou, plus largement, à votre ministère.

** Qu'est-ce que le socle interministériel de logiciels libres ?

Le SILL est le catalogue des logiciels libres recommandés pour toutes
les administrations publiques.

Il est publié par la mission logiciels libres sur [[https://code.gouv.fr/sill][code.gouv.fr/sill]] et
tout agent public est invité à s'y créer un compte pour déclarer ses
usages de logiciels ou se proposer comme référent d'un logiciel.

Voir [[https://code.gouv.fr/sill/readme][code.gouv.fr/sill/readme]] pour plus de détails.

** À quoi sert code.gouv.fr ?
** Avez-vous un glossaire ?
** Existe-t-il une forge interministérielle publique ?
** Pouvez-vous m'aider avec Git ?
** Est-il interdit de publier sur GitHub ?

Non.

** Comment créer un SBOM ("software bill of materials") ?
** Comment détecter et effacer des secrets dans mon historique Git ?
** Qu'est-ce que le "copyleft" ?
** Quelle est la différence entre copyleft faible et fort ?
** Sous quelle licence dois-je publier ma documentation ?
** Quelles langues utiliser pour mon code source et ma documentation ?
** Qu'est-ce qu'un "fork" ?
** Quelle différence entre "algorithme public" et "code source" ?
** Dois-je utiliser Software Heritage ?
** Puis-je créer une marque pour protéger mon logiciel libre ?
** Où trouver des entreprises capables de développer un logiciel libre ?
** Puis-je interdire la réutilisation commerciale des codes sources publiés ?
** Avez-vous un dépôt Git exemplaire ?
** Quelle est la différence entre GitHub et GitLab ?
** Qu'est-ce que SourceHut et pourquoi publier sur cette forge ?
** Commit, fork, AMDAC, etc. : avez-vous un glossaire ?
** En tant qu'administration, comment soutenir un projet libre ?
** Comment aborder le sujet de la communication au sein d'un projet de logiciel libre ?
** Comment faire connaître mon projet de logiciel libre ?
** Deux administrations développent la même chose, que faire ?
** Qu'est-ce qu'un ADMAC ?

AMDAC est l'acronyme de « Administrateur Ministériel des Données, des
Algorithmes et des Codes sources ».  Les AMDACs veillent à appliquer
le principe d'ouverture par défaut des données publiques, incluant les
codes sources des administrations.

** Comment contacter l'AMDAC de mon ministère ?

Voir [[https://www.data.gouv.fr/fr/datasets/liste-des-administrateurs-ministeriels-des-donnees-des-algorithmes-et-des-codes-sources/][la liste des AMDACs]] sur data.gouv.fr.

** Puis-je, en tant que citoyen, exiger d'un organisme public qu'il publie un code source ?

Oui.

** À qui appartiennent les droits d'auteur d'un logiciel développé par une administration ?

S'il est développé par des agents de cette administration, les droits
patrimoniaux appartiennent à l'administration.

S'il est développé par un prestataire et si le contrat a précisé que
l'administration récupère les droits patrimoniaux du logiciel, alors
il appartient à l'administration.

** Qu'est-ce qu'un Open Source Program Office (OSPO) ?

C'est une entité dans une entreprise ou une administration dédiée à la
définition et à la mise en oeuvre d'une stratégie open source pour
cette entreprise ou administration.

Voir [[https://code.gouv.fr/fr/blog/definition-ospo/][notre entrée de blog au sujet des OSPOs]].

** Qu'est-ce qu'un Copyright License Agreement (CLA) ?
** Qu'est-ce qu'un Developer Certificate of Origin (DCO) ?
** Quel processus de contribution mettre en place pour mon projet libre ?
** En tant qu'agent, ai-je le droit de contribuer à un projet libre ?

Oui, si votre responsable est d'accord, il n'y a aucun obstacle à ce
que vous puissiez contribuer à des logiciels libres sur votre temps de
travail.

** Comment mettre fin à un projet libre ?
* Glossaire

** Algorithme

Un algorithme est la description d'une suite d'étapes permettant d'obtenir un résultat à partir d'éléments fournis en entrée (cf. [[https://www.cnil.fr/fr/definition/algorithme][définition de la CNIL]]).

En informatique, cette suite d'étape est une suite d'opérations formelles traitant et produisant des informations.

** Algorithme public

Un algorithme /public/ est un suite opératoire (formelle ou non, informatisée ou non, automatisée ou non) sollicitée pour une décision administrative individuelle envers des personnes physiques ou morales, de droit public ou privé nommément désignées.

Voir le [[https://guides.etalab.gouv.fr/algorithmes/][guide des algorithmes publics]] à l'usage des administrations.

** Bibliothèque

Dans [[https://code.gouv.fr/#/libs][code.gouv.fr]], une bibliothèque est un ensemble de fonctions distribuées sous forme de paquetage via une plateforme dédiée, par exemple https://npmjs.com.

Pour ajouter une bibliothèque dans [[https://code.gouv.fr/#/libs][code.gouv.fr]], il suffit que le compte d'organisation depuis lequel vous publiez cette bibliothèque soit ajouté à [[https://git.sr.ht/~codegouvfr/codegouvfr-sources/tree/master/item/comptes-organismes-publics.yml][ce fichier]].

Vous pouvez écrire à [[mailto:contact@code.gouv.fr][contact@code.gouv.fr]] pour nous indiquer un compte à ajouter.

** Codes sources

Le code source d'un programme informatique est ce qu'écrit une programmeuse ou un programmeur. Il peut s'agir de programmes complexes ou de quelques lignes. Ce code source peut être partagé sous licence libre pour permettre aux autres programmeurs de l'étudier, de le modifier, de le diffuser et de partager leurs améliorations.

** Commun numérique

Un commun numérique est une ressource disponible sous format numérique, gérée par une communauté qui définit, pour cette ressource, des règles d'utilisation et de contribution, et pour la communauté, des règles de participation.

** Dépendances logicielles

Un logiciel intègre souvent des briques logicielles publiées sous licence libre. Celles-ci sont appelées « dépendances ». Ce site permet de parcourir la liste des dépendances de /mise en production/, non les dépendances de /développement/ ; d'autre part, seules sont comprises les dépendances sollicitées par au moins deux dépôts.

Les dépendances listées dans [[https://code.gouv.fr/#/deps][code.gouv.fr]] sont automatiquement identifiées à partir des dépôts référencés sur cette même plateforme. Ne sont prises en compte que les dépendances de premier niveau.

** Dépôt de code source

Un « dépôt » est un espace dans lequel sont publiés les fichiers de code source. C'est ce que vous voyez lorsque vous visitez un lien vers un code source hébergé sur une forge. C'est aussi ce que vous pouvez copier sur votre machine pour l'explorer localement.

Pour ajouter un dépôt dans [[https://code.gouv.fr/#/repos][code.gouv.fr]], envoyez-nous le compte d'organisation GitHub ou le groupe GitLab depuis lequel vous le publiez, nous l'ajouterons dans [[https://git.sr.ht/~codegouvfr/codegouvfr-sources/tree/master/item/comptes-organismes-publics.yml][ce fichier]].

Vous pouvez écrire à [[mailto:contact@code.gouv.fr][contact@code.gouv.fr]] pour nous indiquer un compte à ajouter.

** Étoiles (dans GitHub ou GitLab)

Les « étoiles » (« stars » en anglais) sont un moyen pour les utilisateurs des plates-formes de mettre un dépôt en favori. Pour l'instant, nous collectons cette information sur GitHub, GitLab et les instances de GitLab. Ce n'est pas une mesure de la qualité du code source.

** Fork

Un dépôt « forké » en franglais est un dépôt de code source qui a été développé à partir d'un autre.

** Licence

Une licence logicielle est un contrat passé entre les auteurs d'un logiciel et ses réutilisateurs. Les licences dites « libres » accordent aux utilisateurs le droit de réutiliser le code source d'un logiciel.

** Logiciel libre

Un logiciel libre est un logiciel dont le code source est publié sous l'une des licences reconnues libres par la [[https://www.gnu.org/licenses/licenses.en.html][Free Software Foundation]] ou "open source" par l'[[https://opensource.org/licenses][Open Source Initiative]].

Ces licences ont toutes en commun d'octrayer aux utilisateurs quatre libertés : celle d'/utiliser/ le programme informatique comme on le souhaite, pour toute finalité ; celle d'/étudier et de modifier/ le programme à loisir ; celle de redistribuer des copies du programme à d'autres ; celle de redistribuer des versions modifiées du programme à d'autres.

** Organisation et groupe (dans GitHub ou GitLab)

GitHub permet d'avoir des comptes personnels pour y héberger du code et des « comptes d'organisation ». Un « groupe » est la notion plus ou moins équivalent sur les instance de GitLab. Un organisme remplissant une mission de service public peut avoir un ou plusieurs organisations et/ou groupes sur une ou plusieurs forges.

Pour ajouter une organisation dans [[https://code.gouv.fr/#/groups][code.gouv.fr]], il suffit que le compte d'organisation GitHub ou le groupe GitLab soit ajouté dans [[https://git.sr.ht/~codegouvfr/codegouvfr-sources/tree/master/item/comptes-organismes-publics.yml][ce fichier]].

Vous pouvez écrire à [[mailto:contact@code.gouv.fr][contact@code.gouv.fr]] pour nous indiquer un compte à ajouter.

** Réutilisations

GitHub permet de connaître le nombre de dépôts qui en utilisent un autre : le nombre de ces dépôts est présenté ici dans la colonne "Réutilisations" de la liste des dépôts.

** Secteur public

Les codes sources développés dans le cadre de missions de service public ont vocation à être publiés, dans certains conditions. Ce site propose de chercher dans l'ensemble des codes sources aujourd'hui identifiés comme provenant d'un organisme remplissant une mission de service public. Il a été développé par [[https://www.etalab.gouv.fr][Etalab]].

** Socle interministériel de logiciels libres

Le socle interministériel de logiciels libres (SILL) est le catalogue de référence des logiciels libres recommandés par l'Etat pour toute l'administration.

Voir [[../site/sill.md][cette page]].

** Software Heritage

[[https://www.softwareheritage.org][Software Heritage]] est un projet dont le but est d'archiver tous les codes sources disponibles. Pour chaque dépôt référencé sur ce site, nous donnons le lien vers la version archivée sur Software Heritage.

** Tag

Dans un dépôt de code source géré avec Git, un tag est un label associé à un commit. Ce label peut être annoté ou non. Un tag correspond en général à une nouvelle version du logiciel.

[[https://code.gouv.fr/public/#/tags][code.gouv.fr]] recense les tags des dépôts qui possèdent un fichier =publiccode.yml=, un fichier =CONTRIBUTING.md= ou qui sont à l'origine de la publication de [[https://code.gouv.fr/#/libs][bibliothèques]].
